default: &DEFAULT

  #General
  # For computing compression
  n_params_baseline: None #If None, will be computed
  verbose: True
  arch: 'tfno2d'

  #Distributed computing
  distributed:
    use_distributed: False
    wireup_info: 'mpi'
    wireup_store: 'tcp'
    model_parallel_size: 2
    seed: 666

  # FNO related
  tfno2d:
    data_channels: 3
    n_modes_height: 64
    n_modes_width: 64
    hidden_channels: 64
    out_channels: 1
    lifting_channels: 256
    projection_channels: 256
    incremental_n_modes: None
    n_layers: 4
    domain_padding: None #0.078125
    domain_padding_mode: 'one-sided'
    fft_norm: 'forward'
    norm: 'group_norm'
    skip: 'linear'
    half_prec_fourier: False
    stabilizer: None

    use_mlp: 1
    mlp:
        expansion: 0.5
        dropout: 0

    separable: 0
    preactivation: 0
    factorization: 'cp' #'cp' in best
    joint_factorization: 0
    rank: 0.05
    fixed_rank_modes: False
    implementation: 'factorized'

  # Optimizer
  opt:
    n_epochs: 500
    learning_rate: 1e-3
    training_loss: 'h1'
    weight_decay: 1e-4
    amp_autocast: False
    grad_clip: False # either False/0, or a float that is the max norm of the gradients
    precision_schedule: [125, 375] # Schedule for half, mixed, full-precision Fourier layer

    scheduler_T_max: 500 # For cosine only, typically take n_epochs
    scheduler_patience: 5 # For ReduceLROnPlateau only
    scheduler: 'StepLR' # Or 'CosineAnnealingLR' OR 'ReduceLROnPlateau'
    step_size: 100
    gamma: 0.5

  # Dataset related
  data:
    # folder: '/home/nikola/HDD/NavierStokes/2D'
    folder: '/home/ubuntu/data/navier_stokes/'
    # folder: '/data'
    batch_size: 64
    n_train: 10000
    train_resolution: 128
    n_tests: [2000] #, 1000]
    test_resolutions: [128] #, 1024] 
    test_batch_sizes: [16] #, 1]
    positional_encoding: True

    encode_input: True
    encode_output: False
    num_workers: 0
    pin_memory: False
    persistent_workers: False

  # Patching
  patching:
    levels: 0 #1
    padding: 0 #0.078125
    stitching: True

  # Weights and biases
  wandb:
    log: True
    name: None # If None, config will be used but you can override it here
    group: 'neuraloperator' 
    project: "lowprecision"
    entity: "crwhite" # put your username here
    sweep: False
    log_output: True
    log_test_interval: 1

