default: &DEFAULT

  #General
  # For computing compression
  n_params_baseline: None
  verbose: True
  arch: 'tfno1d'

  #Distributed computing
  distributed:
    use_distributed: False
    wireup_info: 'mpi'
    wireup_store: 'tcp'
    model_parallel_size: 2
    seed: 666

  # FNO related
  tfno1d:
    data_channels: 2
    n_modes_height: 32
    n_modes_width: 32
    hidden_channels: 32
    projection_channels: 64
    n_layers: 4
    domain_padding: None #0.078125
    domain_padding_mode: 'one-sided' #symmetric
    fft_norm: 'forward'
    norm: 'group_norm'
    skip: 'linear'
    implementation: 'factorized'
    separable: 0
    preactivation: 0
    half_prec_fourier: False
    half_prec_inverse: False
    stabilizer: None

    use_mlp: 1
    mlp:
        expansion: 0.5
        dropout: 0

    factorization: 'cp'
    rank: 0.05
    fixed_rank_modes: None
    dropout: 0.0
    tensor_lasso_penalty: 0.0
    joint_factorization: False

  # Optimizer
  opt:
    n_epochs: 300
    learning_rate: 5e-3
    training_loss: 'h1'
    weight_decay: 1e-4
    amp_autocast: False

    scheduler_T_max: 500 # For cosine only, typically take n_epochs
    scheduler_patience: 5 # For ReduceLROnPlateau only
    scheduler: 'StepLR' # Or 'CosineAnnealingLR' OR 'ReduceLROnPlateau'
    step_size: 60
    gamma: 0.5
    precision_schedule: None

  # Dataset related
  data:
    folder: '/home/ubuntu/data/burgers'
    batch_size: 64 #16
    n_train: 5000
    train_resolution: 128
    n_tests: [1000] #[100, 50]
    test_resolutions: [128] #[16, 32]
    test_batch_sizes: [16] #[16, 16]
    positional_encoding: True

    encode_input: True
    encode_output: False

  # Patching
  patching:
    levels: 0
    padding: 0
    stitching: False

  # Weights and biases
  wandb:
    log: True
    name: 'Burgers' # If None, config will be used but you can override it here
    group: 'neuraloperator' 
    project: "lowprecision"
    entity: "crwhite" # put your username here
    sweep: False
    log_output: True
    log_test_interval: 1